### ISSUE TITLE
[feature request] "changeset" support

### ISSUE THREAD

**Issue by Hebilicious** [unjs/changelogen#135]
## Motivation 

It would be great if changelogen had the ability to support an *optional* "changeset" feature. This would allow automated changelog and release logs to include more detailed information about changes. This information can be written for each PR using a markdown file.

## Details : 

Here's how this could work : 

1) When making a PR, add a `.changelogen/[generated-name].md` using the changelogen cli.
2) In this file, write a markdown description of the change.
3) When a release is made, the changelogen cli add these changes into each package CHANGELOG.md, and delete the "changesets".
4) The release text is pre-populated with each "changeset" and can be manually modified.

## Proposed Format : 

Changeset
```md
---
'@nuxt/kit': PRID / commitHash
---

Here we can write a more *detailed* change, using markdown formatting.
| 1 | 2 | 3 |
|---|---|---|
| We | can use | tables |  
```

Changelog with changeset

```md
🚀 Enhancements

- First Change (https://github.com/unjs/changelogen/pull/123)

- Second Change (https://github.com/unjs/changelogen/pull/123)

	Here we can write a more *detailed* change, using markdown formatting.
	| 1 | 2 | 3 |
	|---|---|---|
	| We | can use | tables |  

- Third Change (https://github.com/unjs/changelogen/pull/123))

```

## Related issues

#85 For monorepo support this is able to correctly move the changeset text into each package changelog.
#91 This must be connected to pre-releases
#104 This must be integrated with a github app/action

### Additional information

- [X] Would you be willing to help implement this feature?
```[tasklist]
### Tasks
- [ ] https://github.com/unjs/changelogen/issues/85
- [ ] https://github.com/unjs/changelogen/issues/104
- [ ] https://github.com/unjs/changelogen/issues/91
```
